#!/usr/bin/env bash
# using a while loop and if statement display Best School 10 times but display Hi on the 9th line
count=0

while (( count < 10 ))
do
	echo "Best School"
	if (( count = 9))
	then
		echo "Hi"
	fi	
	(( count++ ))
done 
